# Generated by Django 4.2.2 on 2023-08-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='about',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='behance_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='behance_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='dribbble_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='dribbble_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='github_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='snapchat_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='snapchat_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tiktok_profile',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='website',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='youtube_profile',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('about', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.BigIntegerField(blank=True, default=0)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('instagram_handle', models.CharField(blank=True, default='', max_length=100)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=500)),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=100)),
                ('twitter_link', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_profile', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin_link', models.CharField(blank=True, default='', max_length=500)),
                ('tiktok_profile', models.CharField(blank=True, default='', max_length=100)),
                ('tiktok_link', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp_link', models.CharField(blank=True, default='', max_length=100)),
                ('youtube_profile', models.CharField(blank=True, default='', max_length=100)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=100)),
                ('behance_profile', models.CharField(blank=True, default='', max_length=100)),
                ('behance_link', models.CharField(blank=True, default='', max_length=100)),
                ('facebook_profile', models.CharField(blank=True, default='', max_length=100)),
                ('facebook_link', models.CharField(blank=True, default='', max_length=500)),
                ('github_profile', models.CharField(blank=True, default='', max_length=100)),
                ('github_link', models.CharField(blank=True, default='', max_length=500)),
                ('snapchat_profile', models.CharField(blank=True, default='', max_length=100)),
                ('snapchat_link', models.CharField(blank=True, default='', max_length=500)),
                ('dribbble_profile', models.CharField(blank=True, default='', max_length=100)),
                ('dribbble_link', models.CharField(blank=True, default='', max_length=500)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
