# Generated by Django 4.2.2 on 2023-08-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_username_alter_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_handle',
            new_name='instagram_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_handle',
            new_name='twitter_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='whatsapp_number',
            new_name='whatsapp_profile',
        ),
    ]
