# Generated by Django 4.2.2 on 2023-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_instagram_handle_userprofile_instagram_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=None),
        ),
    ]
