# Generated by Django 4.1.1 on 2022-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypostit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(default='imagename here based on username', max_length=40000),
        ),
        migrations.AddField(
            model_name='profile',
            name='What_i_Do',
            field=models.CharField(default='imagename here based on username', max_length=100),
        ),
    ]
