# Generated by Django 4.1.1 on 2022-10-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypostit', '0005_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
