# Generated by Django 4.1.1 on 2022-10-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypostit', '0010_rename_folower_followerscount_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='following',
            new_name='user',
        ),
    ]
